### ISSUE TITLE
Need `Dockerfile` for `sandy1709/catuserbot:slim-buster`

### ISSUE THREAD

**Issue by advnpzn** [TgCatUB/catuserbot#322]
I need `Dockerfile` used to build [sandy1709/catuserbot:slim-buster](https://hub.docker.com/layers/sandy1709/catuserbot/slim-buster/images/sha256-d289fd6ca4f0759b261bcb21ad3468a119a92ba338c43ec5d0f44c0292167301?context=explore) to build image for `arm64/v8/linux` arch.

**Comment by Jisan09** [comment]
We changed docker from  [sandy1709/catuserbot:slim-buster](https://hub.docker.com/layers/sandy1709/catuserbot/slim-buster/images/sha256-d289fd6ca4f0759b261bcb21ad3468a119a92ba338c43ec5d0f44c0292167301?context=explore)  to [catub/catuserbot:latest](https://hub.docker.com/r/catub/catuserbot/tags) and this support multi-arch.
