### ISSUE TITLE
Can't use inline commands in private chats and private groups

### ISSUE THREAD

**Issue by ImDimii** [TgCatUB/catuserbot#330]
Hi, everyone, my issue is that i can't execute inline commands of the bot in private chats and private groups. That's the error that the console shows me. Thanks in advance for the help.
![image](https://user-images.githubusercontent.com/95036781/234064116-06e34b11-7354-4c3d-a3ef-26169877abcc.png)

**Comment by Jisan09** [comment]
change the group to a  super group,  i.e  group id start with -100.
If still issue there after that contact support : <https://t.me/catuserbot_support>
