### ISSUE TITLE
Animechan API migrated to another URL

### ISSUE THREAD

**Issue by luisbandalap** [TgCatUB/catuserbot#363]
Hello,

Original animechan API url was https://animechan.vercel.app/api/random but now is https://animechan.xyz/api/random 

Changing it should allow alive plugin's {ANIME} caption to work again.

https://github.com/TgCatUB/catuserbot/blob/2e521b3227e9075979d0112f07e876f846910d3e/userbot/plugins/alive.py#L54C29-L54C29

**Comment by Jisan09** [comment]
Open PR on beta : )

**Comment by sandy1709** [comment]
Merged into beta.

marking as closed.
